# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Command-Viz
version:      0.02
version_from: lib/Devel/Command/Viz.pm
installdirs:  site
requires:
    Devel::Command:                0
    GraphViz::Data::Structure:     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
